### ISSUE TITLE
wrong reference ?

### ISSUE THREAD

**Issue by vin-d** [40ants/log4cl-extras#1]
as I understood log4cl-json is now named log4cl-extras
so here https://github.com/40ants/log4cl-extras/blob/79dfa791e91a9021ae352167eff58cd3c34d7260/log4cl-extras-test.asd#L5
the reference should be to log4cl-extras instead

**Comment by svetlyak40wt** [comment]
Thank you! I've fixed this in the https://github.com/40ants/log4cl-extras/commit/fa260bbe4f5300ebcf59e037c79c6e0f7cb70e45 commit.
