### ISSUE TITLE
Question : log4cl-extras/context:with-fields and log4slime log messages

### ISSUE THREAD

**Issue by vin-d** [40ants/log4cl-extras#3]
Hi,
I'm having difficulties to figure out my log architecture to adapt and use log4cl-extras with json logging but still keep a non json log4slime compatibility

Typically my existing logs is currently just the message built with tokens ("format t like"), and this way is great for development as I have emacs with slime and log4slime.

if I decide to use log4cl-extras for production I would strip down the "token/variables" from my current log message to use /context:with-fields

The problem is then that I miss those fields in log4slime.
What would be an elegant solution so that the fields are injected in the message for the log4slime configured logger.
The only thing I see is to make a wrapper above (log:info "my message") and use the wrapper, and recreate/replace the context/with-field method by my own implementation when I'm in development - mode so that the field gets injected in the message content.

I feel it's not an elegant solution and more or less an hack to override the /context:with-fields.
Would there be another solution  ?
(i am quite a beginner in Lisp and don't master log4cl).

**Comment by svetlyak40wt** [comment]
Probably, I misunderstand you. Do you want to hide tokens in production but show them in development mode?

**Comment by vin-d** [comment]
no, 
I'd like in development to have the context fields displayed when I write a log as in 

```
(log4cl-extras/context:with-fields (:|request_id| request-id)
   (log:info "my logged message))
```
I can have that with a config of `(this-console :layout json) `
but then I loose my log4slime formatting with the "hyper-link" that links back to the source code from the slime REPL.

I don't know how log4slime sets that format/layout, but I guess I have to tweak it somewhere so it uses the log4cl-extras/context:get-fields when it writes the log.

**Comment by svetlyak40wt** [comment]
Actually, it is better to use `this-console :layout :plain` when you want to see logs in the REPL.

I'm not using SLIME, I use SLY instead, so never used this feature of hyper-links, because they aren't supported in SLY.

Plain formatted should be improved to do what you want. Also, there should be a way to add information about file and line number. It will be useful both for json and plain formatters.

Feel free to experiment with that and send a pull request to discuss these changes.

**Comment by svetlyak40wt** [comment]
By the way, to protect passwords from being displayed in the stack traces, I recommend taking a look at [secret-values](https://40ants.com/lisp-project-of-the-day/2020/09/0186-secret-values.html) library.
