### ISSUE TITLE
Show package, file and function information in plain and json formats

### ISSUE THREAD

**Issue by svetlyak40wt** [40ants/log4cl-extras#9]
@sabracrolleton:

By default, log4cl shows the package, file and function in the logged information, plus a message that I can insert info into. If I use the example setup for log4cl-extras for plain, I lose that automatic package, file and function information and have to manually insert it back using with-fields. How would I get that default capability back?

@svetlyak40wt:

This information is still absent because I didn't figured out an easy way to get it. I'd like to return it back too.

**Comment by svetlyak40wt** [comment]
This issue was closed in https://github.com/40ants/log4cl-extras/pull/10 pull-request.

**Comment by Hexstream** [comment]
Should close this, then. :)

(It seems GitHub recognizes `closes #9` but not `closes issue #9`.)
